kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: prodarcab
  name: allow-ui 
spec:
  podSelector:
    matchLabels: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              role: production
